from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json
import random

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
def connect_database():
    cloud_config= {
        'secure_connect_bundle': 'Astra prompts results.zip'
    }

    # This token JSON file is autogenerated when you download your token, 
    # if yours is different update the file name below
    with open("Prompts Results Token.json") as f:
        secrets = json.load(f)

    CLIENT_ID = secrets["clientId"]
    CLIENT_SECRET = secrets["secret"]

    auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
    session = cluster.connect()
    return session


def insert_prompt(session, prompt, response):
    id = random.randint(0, 1000000)
    session.execute(
        """
        INSERT INTO prompts_results.prompts (id, prompt, response)
        VALUES (%s, %s, %s)
        """,
        (id, prompt, response)
    )
# session.execute(
#   """
#   INSERT INTO prompts_results.prompts (id, prompt, response)
#   VALUES (%s, %s, %s)
#   """,
#   (id, prompt, response)
# )

def read_history(session):
    rows = session.execute("SELECT * FROM prompts_results.prompts")
    for row in rows:
        print(row.id, row.prompt, row.response)
    
# row = session.execute("select release_version from system.local").one()
# if row:
#   print(row[0])
# else:
#   print("An error occurred.")